# Generated by Django 4.1.5 on 2023-01-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('rut', models.CharField(max_length=50, verbose_name='Rut')),
                ('telefono', models.IntegerField(verbose_name='Celular')),
                ('nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('direccion', models.CharField(max_length=1000)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='ficha', verbose_name='Adjuntar imagen')),
                ('morbido', models.BooleanField(null=True, verbose_name='Morbidos')),
                ('cronico', models.CharField(choices=[('NO', 'NO'), ('XD', 'XD'), ('HTA', 'HTA')], default='NO', max_length=50, null=True, verbose_name='Enf. Cronicas')),
                ('alergia', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Alergias')),
                ('medicamentos', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Medicamentos')),
                ('atencion', models.DateField(verbose_name='Ultima Atención Podologica')),
                ('amputacion', models.BooleanField(blank=True, null=True, verbose_name='Amputacion')),
            ],
        ),
    ]
