# Generated by Django 4.1.5 on 2023-01-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='amputacion',
            field=models.CharField(blank=True, choices=[('NO', 'NO'), ('SI', 'SI')], default='NO', max_length=10, null=True, verbose_name='Amputacion'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='morbido',
            field=models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], default='NO', max_length=10, null=True, verbose_name='Morbidos'),
        ),
    ]
