# Generated by Django 4.1.5 on 2023-01-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0002_alter_ficha_amputacion_alter_ficha_morbido'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='observacion',
            field=models.CharField(default='', max_length=100000, verbose_name='Observaciones'),
            preserve_default=False,
        ),
    ]
