# Generated by Django 4.1.5 on 2023-01-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0003_ficha_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='ficha', verbose_name='Adjuntar imagen'),
        ),
    ]
