# Generated by Django 4.1.5 on 2023-01-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0005_alter_ficha_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='ficha', verbose_name='Adjuntar imagen'),
        ),
    ]
