# Generated by Django 4.1.5 on 2023-01-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0007_alter_ficha_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='ficha', verbose_name='Antes'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='ficha', verbose_name='Despues'),
        ),
    ]
