# Generated by Django 4.1.5 on 2023-01-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0008_alter_ficha_imagen_alter_ficha_imagen2'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to='ficha', verbose_name='Despues'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='ficha', verbose_name='Proceso'),
        ),
    ]
