# Generated by Django 4.1.5 on 2023-01-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=9)),
                ('fecha_reserva', models.DateField()),
                ('hora_reserva', models.CharField(choices=[('12:00 a 13:00', '12:00 a 13:00'), ('13:00 a 14:00', '13:00 a 14:00'), ('11:00 a 12:00', '11:00 a 12:00'), ('14:00 a 15:00', '14:00 a 15:00'), ('18:00 a 19:00', '18:00 a 19:00'), ('19:00 a 20:00', '19:00 a 20:00'), ('16:00 a 17:00', '16:00 a 17:00'), ('17:00 a 18:00', '17:00 a 18:00'), ('15:00 a 16:00', '15:00 a 16:00'), ('0', 'Seleccione hora'), ('10:00 a 11:00', '10:00 a 11:00')], default=0, max_length=50)),
                ('tratamiento', models.CharField(choices=[('0', 'Seleccione tratamiento'), ('Pie de atleta', 'Pie de atleta'), ('Uña encarnada', 'Uña encarnada'), ('Ojo de gallo', 'Ojo de gallo'), ('Hongos en las uñas', 'Hongos en las uñas'), ('Mantención podológica', 'Mantención podológica')], default=0, max_length=100)),
                ('domicilio', models.BooleanField()),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
            },
        ),
    ]
