# Generated by Django 4.1.5 on 2023-01-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0002_alter_reservas_hora_reserva_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservas',
            options={},
        ),
        migrations.AlterField(
            model_name='reservas',
            name='fecha_reserva',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='hora_reserva',
            field=models.CharField(choices=[('10:00 a 11:00', '10:00 a 11:00'), ('11:00 a 12:00', '11:00 a 12:00'), ('12:00 a 13:00', '12:00 a 13:00'), ('13:00 a 14:00', '13:00 a 14:00'), ('14:00 a 15:00', '14:00 a 15:00'), ('15:00 a 16:00', '15:00 a 16:00'), ('16:00 a 17:00', '16:00 a 17:00'), ('17:00 a 18:00', '17:00 a 18:00'), ('18:00 a 19:00', '18:00 a 19:00'), ('19:00 a 20:00', '19:00 a 20:00')], max_length=50, verbose_name='Hora de atención'),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='tratamiento',
            field=models.CharField(choices=[('Pie de atleta', 'Pie de atleta'), ('Uña encarnada', 'Uña encarnada'), ('Ojo de gallo', 'Ojo de gallo'), ('Hongos en las uñas', 'Hongos en las uñas'), ('Mantención podológica', 'Mantención podológica')], max_length=100),
        ),
    ]
