# Generated by Django 4.1.5 on 2023-01-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0005_reservas_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='precio_total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
