# Generated by Django 4.1.5 on 2023-01-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0006_reservas_precio_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='cantidad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
